### ISSUE TITLE
Pipeline questions

### ISSUE THREAD

**Issue by cindywen96** [xuanyao/GBAT#1]
Hi I have a few questions running the pipeline:

1. **(SOLVED)** Could you provide the code to generate `hg19.mappability.filtered.gtf`, i.e. given a GTF and ENCODE 36 kmer mappability file, to generate a filtered GTF? 

2. In `get_rdata.r`, for function `count_read`, should it be `return(length(which(x >= 1)))` instead of 0.5 if filter is set as >1 CPM as stated in the paper?

3. In `get_rdata.r`,
```
all=cpm[keep.flag,]
dat=dat[keep.flag,]

gene_length=abs(dat$Length)

for(i in 1:ncol(all)){
all[,i]=(all[,i]/gene_length)/(total_count[i]/1000000)
}
```
here `all` is converted to CPM from counts. I think there is something wrong with the TPM calculation. Specifically, `total_count` should be CPM scaled by gene length. Or alternatively, keep `all` as counts, and `total_counts` as counts scaled by gene length

**Comment by xuanyao** [comment]
Hi Cindy,

Thanks for pointing this out. You are right, please do the CPM filtering
and TPM calculations as you described. I will update the scripts on github
soon too.

Best,
Xuanyao

**Comment by cindywen96** [comment]
Thank you for your reply, Xuanyao!
I have another question regarding sva and wanted to make sure I understand the pipeline correctly. In `rule sva`, unsupervised gene expression SVA is calculated; then in `rule cvBLUP`, 20 SVA is combined with other covariates (gPC, sex, age, etc.) to predict gene expression. 
For `rule cor`, I noticed there are two scripts, `cal_cor.R` and `cal_cor_covar.R`. In both, supervised gene expression SVA is calculated. If there are other covariates than SVA I wanted to include in the linear regression (e.g. gPC, age, etc. as I included in cvBLUP), I want to use `cal_cor_covar.R`, correct?

**Comment by xuanyao** [comment]
Hi Cindy,

That's right. You can use cal_cor_covar.R if you have other covariates
other than supervised SVA, though I remembered the results from cal_cor.R
is very similar.

Best,
Xuanyao

**Comment by cindywen96** [comment]
Hi Xuanyao,

Thanks for updating the get_rdata.r script. For TPM calculation, `gene_length` is not scaled by 1000 base. Is that intended? Also I noticed the standardization code is removed. If I want to normalize TPM to standard normal, should I keep the standardization processing after `normalize.quantiles`?

**Comment by xuanyao** [comment]
Hi Cindy,

Which version of get_rdata.r script are you using? I believe the current
script has two normalization steps:

#all=median.normalize.log(all)
library(preprocessCore)
library(phenix)
#all <- normalize.quantiles(as.matrix(all))
all <- normalize.quantiles(as.matrix(all))
all.t=t(all)
all2=quantnorm(all.t)
all=t(all2)

normalize.quantiles does quantile normalization, and quantnorm does the
standardization you are referring to. You can include the 1000 scaling, but
it won't change the gene quantification in the end.


Best,
Xuanyao

**Comment by cindywen96** [comment]
I see! Thank you!!
